
checking =====================  EXPERIMENTAL PROPOSALS

checking SEARCH ORDER SPECIFICATION AND CONTROL

checks:  ONLY  FORTH  ALSO  ORDER  WORDS   FORGET  DEFINITIONS SEAL

checking DEFINITION FIELD ADDRESS CONVERSION OPERATORS

checks:  >BODY  >NAME  >LINK  BODY>  NAME>  LINK> N>LINK L>NAME

